window.RV_STOPS = (window.RV_STOPS || []).concat([
  {
    id: "hocking",
    name: "Hocking Hills",
    dates: "Oct 6–11",
    image: "images/hocking-hills.jpg",
    campground: {
      name: "Hocking Hills KOA Holiday",
      url: "https://koa.com/campgrounds/hocking-hills/",
      map: "https://www.google.com/maps/search/?api=1&query=Hocking+Hills+KOA+Holiday",
      note: "Full hookups and 50A. Published max pull-through length is 40 ft, so confirm coach fit before booking.",
    },
    activities: [
      {
        who: "Together",
        name: "Old Man's Cave → Cedar Falls",
        facts: "Major hike · stairs/grade · no scramble",
        desc: "The marquee Hocking hike: gorge, waterfalls and sandstone features. This is one of the best uses of a vacation day.",
        url: "https://www.hockinghills.com/old_mans_cave.html",
      },
      {
        who: "Together",
        name: "Ash Cave",
        facts: "Very easy lower trail · optional grade",
        desc: "Huge recess cave with an easy lower approach. Excellent scenery-to-effort ratio for an arrival evening or second outing.",
        url: "https://www.hockinghills.com/ash_cave.html",
      },
      {
        who: "Together",
        name: "Conkle's Hollow — gorge floor",
        facts: "Short · gentle · avoid rim exposure",
        desc: "Take the lush gorge-floor trail and skip the exposed rim unless you specifically want edge terrain that day.",
        url: "https://www.hockinghills.com/conkles_hollow.html",
      },
      {
        who: "Together",
        name: "Rock House",
        facts: "≈1 mi · steeper stairs",
        desc: "Shorter, steeper and atmospheric sandstone “house”; good paired with another stop.",
        url: "https://www.hockinghills.com/rock_house.html",
      },
      {
        who: "Sue daytime",
        name: "Inn & Spa at Cedar Falls",
        facts: "Spa · reservation · 2–4 hr",
        desc: "The strongest truly independent Sue day in Hocking—massage or treatment plus a relaxed lunch.",
        url: "https://www.innatcedarfalls.com/spa/",
      },
      {
        who: "Sue daytime",
        name: "Nelsonville historic square",
        facts: "Coffee · shops · art",
        desc: "Historic square, local shops and Stuart’s Opera House; an easy low-pressure outing.",
        url: "https://stuartsoperahouse.org/",
      },
      {
        who: "Sue daytime",
        name: "Athens + Ohio University",
        facts: "College town · cafés · longer outing",
        desc: "A fuller workday option with campus energy, bookstores, food and places to linger.",
        url: "https://athensohio.com/",
      },
    ],
  },
]);
