window.RV_STOPS = (window.RV_STOPS || []).concat([
  {
    id: "yellow",
    name: "Yellow Springs",
    dates: "Oct 2–6",
    image: "images/yellow-springs.jpg",
    campground: {
      name: "John Bryan State Park",
      url: "https://ohiodnr.gov/wps/portal/gov/odnr/go-and-do/plan-a-visit/find-a-property/john-bryan-state-park",
      map: "https://www.google.com/maps/search/?api=1&query=John+Bryan+State+Park+Ohio",
      note: "Electric sites, dump station and direct trail access; a good 4-night electric-only stop.",
    },
    activities: [
      {
        who: "Together",
        name: "Clifton Gorge + John Bryan",
        facts: "3–5 mi flexible · easy–moderate · some stairs",
        desc: "Wooded gorge and forest walking right by camp. No scrambling is needed, and it is easy to shorten for an after-work outing.",
        url: "https://www.greenecountyohio.org/listing/clifton-gorge/794/",
        image: "images/clifton-gorge.jpg",
      },
      {
        who: "Together",
        name: "Little Miami Scenic Trail",
        facts: "Paved · flat/gentle · e-bike ideal",
        desc: "A long paved corridor with lots of turnaround choices. A 20–35 mile e-bike day fits your preferences very well.",
        url: "https://www.traillink.com/trail/little-miami-scenic-trail/",
        image: "images/little-miami-trail.jpg",
      },
      {
        who: "Evening",
        name: "Little Art Theatre",
        facts: "2–3 hr · indoor",
        desc: "Historic art-house theatre for independent films, documentaries and special events after work.",
        url: "https://www.littleart.com/",
        image: "images/little-art-theatre.webp",
      },
      {
        who: "Sue daytime",
        name: "Xenia Avenue shops & cafés",
        facts: "Walkable · 2–4 hr",
        desc: "Independent shops, coffee and lunch in a compact downtown. Very low-friction solo time: park once and wander.",
        url: "https://www.yellowspringsohio.org/",
        image: "images/xenia-avenue.jpg",
      },
      {
        who: "Sue daytime",
        name: "Glen Helen",
        facts: "Flexible walking · nature preserve",
        desc: "Short nature walks immediately beside town, easy to combine with coffee or lunch without making it a major hike day.",
        url: "https://glenhelen.org/",
        image: "images/glen-helen.jpg",
      },
      {
        who: "Sue daytime / evening",
        name: "Antioch / Foundry events",
        facts: "Talks · performances · campus",
        desc: "Lectures, music and performances—the sort of small-venue programming Sue said she likes.",
        url: "https://antiochcollege.edu/foundry-theater/",
        image: "images/antioch-foundry.jpg",
      },
    ],
  },
]);
