window.RV_ITINERARY = [
  {
    date: "2026-10-02",
    stop: "Yellow Springs",
    kind: "Travel / work-lite",
    day: "Drive Canton → Yellow Springs. Settle into John Bryan State Park.",
    evening:
      "Downtown Yellow Springs stroll + dinner / Little Art Theatre if something appeals.",
  },
  {
    date: "2026-10-03",
    stop: "Yellow Springs",
    kind: "Shared weekend",
    day: "Clifton Gorge + John Bryan hike, flexible 3–5 miles.",
    evening: "Downtown cafés, shops, then an easy evening.",
  },
  {
    date: "2026-10-04",
    stop: "Yellow Springs",
    kind: "Shared weekend",
    day: "Little Miami Scenic Trail e-bike ride; choose distance by weather/energy.",
    evening: "Relaxed dinner; Foundry/Little Art event if scheduled.",
  },
  {
    date: "2026-10-05",
    stop: "Yellow Springs",
    kind: "Workday",
    day: "Sue: Xenia Avenue shops/cafés + Glen Helen. Patrick works 7–10 and 11–4.",
    evening: "Meet downtown after 4; short walk or movie.",
  },
  {
    date: "2026-10-06",
    stop: "Hocking Hills",
    kind: "Short move + work",
    day: "Early move Yellow Springs → Hocking Hills. Sue: spa / Logan / settle in while Patrick works 11–4.",
    evening: "Ash Cave near golden hour if energy allows.",
  },
  {
    date: "2026-10-07",
    stop: "Hocking Hills",
    kind: "Workday",
    day: "Sue: Inn & Spa at Cedar Falls or Nelsonville square. Patrick works.",
    evening: "Rock House or easy scenic outing after 4.",
  },
  {
    date: "2026-10-08",
    stop: "Hocking Hills",
    kind: "Workday",
    day: "Sue: Athens + Ohio University cafés / shops / campus. Patrick works.",
    evening: "Quiet campground night or Stuart's Opera House if schedule fits.",
  },
  {
    date: "2026-10-09",
    stop: "Hocking Hills",
    kind: "Vacation day 1",
    day: "Old Man's Cave → Cedar Falls shared hike; make this the signature Hocking day.",
    evening: "Dinner out; low-key evening.",
  },
  {
    date: "2026-10-10",
    stop: "Hocking Hills",
    kind: "Shared weekend",
    day: "Conkle's Hollow gorge floor + whatever Hocking highlight weather favors.",
    evening: "Sunset / relaxed dinner.",
  },
  {
    date: "2026-10-11",
    stop: "New River Gorge",
    kind: "Weekend travel",
    day: "Drive Hocking Hills → Fayetteville / Rifrafters. Stop early if the mountain leg feels tiring.",
    evening: "Fayetteville dinner and short walk.",
  },
  {
    date: "2026-10-12",
    stop: "New River Gorge",
    kind: "Vacation day 2",
    day: "Endless Wall + Long Point, weather permitting.",
    evening: "Fayetteville evening.",
  },
  {
    date: "2026-10-13",
    stop: "New River Gorge",
    kind: "Workday",
    day: "Sue: Fayetteville cafés/shops + Tamarack Marketplace. Patrick works.",
    evening: "Grandview overlook / short walk after 4.",
  },
  {
    date: "2026-10-14",
    stop: "New River Gorge",
    kind: "Workday",
    day: "Sue: Bridge Walk or African American Heritage Auto Tour. Patrick works.",
    evening: "Easy dinner; pack for mountain move.",
  },
  {
    date: "2026-10-15",
    stop: "Asheville",
    kind: "Travel day",
    day: "No-pressure drive Fayetteville → Asheville East KOA; keep coach on major routes.",
    evening: "Simple dinner near camp.",
  },
  {
    date: "2026-10-16",
    stop: "Asheville",
    kind: "Vacation day 3",
    day: "Shared Blue Ridge / mountain hike day using current open-road status.",
    evening: "Downtown Asheville dinner + live music.",
  },
  {
    date: "2026-10-17",
    stop: "Asheville",
    kind: "Shared weekend",
    day: "NC Arboretum + River Arts District.",
    evening: "Orange Peel / Grey Eagle / Wortham Center if a good show is on.",
  },
  {
    date: "2026-10-18",
    stop: "Asheville",
    kind: "Shared weekend",
    day: "Biltmore house & gardens or a second mountain outing.",
    evening: "Relaxed downtown evening.",
  },
  {
    date: "2026-10-19",
    stop: "Asheville",
    kind: "Vacation day 4",
    day: "Flexible shared day: best-weather hike, Biltmore, or long art/food day.",
    evening: "Live music / theatre.",
  },
  {
    date: "2026-10-20",
    stop: "Asheville",
    kind: "Workday",
    day: "Sue: Asheville Art Museum + downtown cafés/galleries. Patrick works.",
    evening: "Meet downtown after 4; dinner + short music set.",
  },
  {
    date: "2026-10-21",
    stop: "Asheville",
    kind: "Workday",
    day: "Sue: Grove Park Inn spa or River Arts District studios. Patrick works.",
    evening: "Easy shared dinner; early night before move.",
  },
  {
    date: "2026-10-22",
    stop: "Chattanooga",
    kind: "Travel day",
    day: "Drive Asheville → Raccoon Mountain Campground; daylight and no rush.",
    evening: "Bluff View / riverfront dinner if arrival is easy.",
  },
  {
    date: "2026-10-23",
    stop: "Chattanooga",
    kind: "Vacation day 5",
    day: "Tennessee Riverwalk e-bike ride + riverfront exploration.",
    evening: "Live music or Tivoli / Walker Theatre.",
  },
  {
    date: "2026-10-24",
    stop: "Chattanooga",
    kind: "Shared weekend",
    day: "Lookout Mountain + Point Park; add Sunset Rock only if trail/energy fit.",
    evening: "Downtown dinner.",
  },
  {
    date: "2026-10-25",
    stop: "Chattanooga",
    kind: "Shared weekend",
    day: "Tennessee Aquarium + Walnut Street Bridge / riverfront.",
    evening: "Music, comedy, or relaxed Bluff View evening.",
  },
  {
    date: "2026-10-26",
    stop: "Chattanooga",
    kind: "Vacation day 6",
    day: "Flexible shared day: aquarium if not done, caverns, hike, or long bike ride.",
    evening: "Hunter Museum late-hours style evening if timing fits.",
  },
  {
    date: "2026-10-27",
    stop: "Chattanooga",
    kind: "Workday",
    day: "Sue: Hunter Museum + Bluff View + riverfront cafés. Patrick works.",
    evening: "Meet for dinner / show after 4.",
  },
  {
    date: "2026-10-28",
    stop: "Lexington",
    kind: "Travel day",
    day: "Drive Chattanooga → Kentucky Horse Park; longer interstate move, no deadline pressure.",
    evening: "Campground walk / easy dinner.",
  },
  {
    date: "2026-10-29",
    stop: "Lexington",
    kind: "Workday",
    day: "Sue: Kentucky Horse Park. Patrick works.",
    evening: "Downtown Lexington dinner / Lyric programming.",
  },
  {
    date: "2026-10-30",
    stop: "Lexington",
    kind: "Vacation day 7",
    day: "Legacy Trail e-bike ride + Keeneland / horse-country drive.",
    evening: "Downtown evening.",
  },
  {
    date: "2026-10-31",
    stop: "Lexington",
    kind: "Shared weekend",
    day: "Raven Run hike or another horse-country outing.",
    evening: "Halloween / local event if appealing.",
  },
  {
    date: "2026-11-01",
    stop: "Lexington",
    kind: "Shared weekend",
    day: "21c Museum Hotel + downtown, relaxed brunch and wandering.",
    evening: "Quiet evening; prep for short move.",
  },
  {
    date: "2026-11-02",
    stop: "Cincinnati / Lebanon",
    kind: "Short move + work",
    day: "Early Lexington → Lebanon move. Sue: historic Lebanon. Patrick works 11–4.",
    evening: "Easy local dinner.",
  },
  {
    date: "2026-11-03",
    stop: "Cincinnati / Lebanon",
    kind: "Workday",
    day: "Sue: Findlay Market + Over-the-Rhine cafés/shops. Patrick works.",
    evening: "Comedy / music / theatre after 4.",
  },
  {
    date: "2026-11-04",
    stop: "Cincinnati / Lebanon",
    kind: "Workday",
    day: "Sue: Contemporary Arts Center or Museum Center. Patrick works.",
    evening: "Downtown dinner / show.",
  },
  {
    date: "2026-11-05",
    stop: "Cincinnati / Lebanon",
    kind: "Workday",
    day: "Sue: Freedom Center if she wants it solo, or Lebanon spa/café day. Patrick works.",
    evening: "Light evening; save energy for Friday.",
  },
  {
    date: "2026-11-06",
    stop: "Cincinnati / Lebanon",
    kind: "Vacation day 8",
    day: "Shared Freedom Center + riverfront, or Little Miami e-bike day if weather is great.",
    evening: "Final-trip dinner + comedy/music.",
  },
  {
    date: "2026-11-07",
    stop: "Home",
    kind: "Travel home",
    day: "Drive Lebanon → Canton. Comfortable Saturday finish.",
    evening: "Home.",
  },
];
